version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    major-update:
      applies-to: version-updates
      update-types:
      - "major"
